# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Numerical-React CI/CD

on:
    push:
        branches: [main]
jobs:
    push_to_registry:
        name: Push Numerical-React to Github
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Docker Login
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - name: Docker Build
              run: |
                  docker build . -t theboss38/numerical-react:latest
            - name: Docker Push
              run: |
                  docker push theboss38/numerical-react:latest
